credentials:
  usernames:
    higia:
      email: angel.mola@higia.ai
      name: higia
      password: abc # To be replaced with hashed password
cookie:
  expiry_days: 30
  key: random_signature_key # Must be string
  name: random_cookie_name
preauthorized:
  emails:
  - angel.mola@higia.ai
